#:schema node_modules/wrangler/config-schema.json
name = "lista-v3"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "lista_db"
database_id = "25b87c1b-c6fd-4dfc-8858-5a25388723a6"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "my-emdash-media"

# Observability
[observability]
enabled = true

# Vars
[vars]
NEXT_PUBLIC_APP_URL = "https://lista-v3.pages.dev"
